### PR TITLE
Use different typedefs for encoded capability and integer register numbers

### PR DESCRIPTION
**Pull request by arichardson**
This should make it easier to generate various tables such as disassembly,
encoding overviews, etc.

No functional change.

### CODE REVIEW

**Review by nwf — APPROVED** [review]

**Comment by rmn30** [comment]
Looks fine. I will also change the types of `readCapReg` etc. It would be really nice if we could use the type system to get an error if we use the wrong type alias but Sail doesn't work like that. We could do that if we used enumerations instead of a typedef but would have to add a lot of conversions in the decode I think.

**Comment by arichardson** [comment]
> Looks fine. I will also change the types of `readCapReg` etc. It would be really nice if we could use the type system to get an error if we use the wrong type alias but Sail doesn't work like that. We could do that if we used enumerations instead of a typedef but would have to add a lot of conversions in the decode I think.

Yes, I agree some kind of strong typedef would be nice to avoid errors.

**Comment by rmn30** [comment]
In principle we should also change the types of all the instruction ast constructors to match but since Sail doesn't mind I don't think there is much point.

**Comment by nwf** [comment]
Much longer term, but perhaps Sail should grow something like Haskell's `newtype`, `coerce`, and `deriving` mechanisms for this kind of translucent aliasing?  Maybe that's trickier in a dependently typed system?

**Pull request merged**
